title: "Ben's Blog"

author:
  name: Benjamin Lehmann

description: >
  The source for this blog is available at github.com/bclehmann/bclehmann.github.io

markdown: kramdown
kramdown:
  math_engine: katex

permalink: pretty

# Github pages version of jekyll is hilariously out of date and breaks everything
# We also have to pin a commit hash because this PR bricks CI: https://github.com/jekyll/minima/pull/686
remote_theme: jekyll/minima@41b97699af658128fa9983e5312ca5516641f335

minima:
  skin: auto
  social_links:
    github: bclehmann
    linkedin: benjamin-lehmann-a87772206

plugins:
  - jekyll-sitemap
  - jekyll-feed
